# Generated by Django 5.0.3 on 2024-04-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_subject_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.IntegerField()),
                ('gamename', models.CharField(max_length=20)),
                ('gamelevel', models.CharField(max_length=20)),
                ('gamescore', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
